export * from './ajax/var'
export * from './browser/var'
// export * from './encrypt/var'
export * from './commonUtil/var'
export * from './router/var'
export * from './url/var'
export * from './user/var'