export * from './dealRequestData'
export * from './dicget'
export * from './getConfig'
export * from './getUser'
export * from './getXzqh'
export * from './getXzqhmc'
export * from './possessMkqx'