export * from './getDzpjConfig'
export * from './getKpJgConfig'
export * from './getKpRes'
export * from './isOpenFp'
export * from './isPrintPz'
export * from './kping'
export * from './setDzpjConfig'
export * from './setKpJgConfig'