export * from './getDzpjConfig'
export * from './getDzpjKpJgConfig'
export * from './getDzpjKpRes'
export * from './isOpenFp'
export * from './isPrintPz'
export * from './kping'
export * from './setDzpjConfig'
export * from './setKpJgConfig'