export * from './get'
export * from './post'
export * from './api'
export * from './upload'
export * from './deal'
export * from './magic'
export { ajaxSuccessCode, setAjaxSuccessCode, setJqMode, setAjaxContentType, ajaxErrorCode } from '../var'