export { mathInit } from '../var'
export * from './add'
export * from './divide'
export * from './getRes'
export * from './multiply'
export * from './reDivide'
export * from './reSubtract'
export * from './subtract'
export * from './toFiexd'